// Sentieri: offline support. Generated by make_sw.py, do not edit by hand.
var VERSION = '722b602339';
var SHELL = 'app-' + VERSION;
var TILES = 'tiles-v1';
var DATA = 'data-v1';
var MAX_TILES = 8000;
var MAX_DATA = 1500;
var FILES = [
"./",
"index.html",
"hiking.css",
"manifest.webmanifest",
"icon-192.png",
"icon-512.png",
"build/bundle.css",
"build/bundle.min.css",
"build/help-BaZENAXx.js",
"build/help-CuxUNP-H.js",
"build/helppages-B0S3pL_k.js",
"build/helppages-B2RwWpsw.js",
"build/helppages-B9wYAQHq.js",
"build/helppages-BOgkKf8v.js",
"build/helppages-BTngNWz7.js",
"build/helppages-BTvQaRRG.js",
"build/helppages-BgIPFRbg.js",
"build/helppages-BtbhFrkg.js",
"build/helppages-Bty5QUuh.js",
"build/helppages-BvjwlLCD.js",
"build/helppages-BxeXCxLu.js",
"build/helppages-C71Jdl6v.js",
"build/helppages-C95N1Vpk.js",
"build/helppages-CBCHZ20i.js",
"build/helppages-CBMzF3fC.js",
"build/helppages-CDDwP-nv.js",
"build/helppages-CFkCy6MU.js",
"build/helppages-CKINp0yI.js",
"build/helppages-CKZq8NZu.js",
"build/helppages-CLfkjfQV.js",
"build/helppages-CPZzHetB.js",
"build/helppages-CRlmhW6e.js",
"build/helppages-CSOh9PJr.js",
"build/helppages-CWP-DFcW.js",
"build/helppages-CeofYUmO.js",
"build/helppages-CwUbAP0L.js",
"build/helppages-D26LbTo5.js",
"build/helppages-D8Eg2f9-.js",
"build/helppages-DBvzJHVZ.js",
"build/helppages-DEHrBW1a.js",
"build/helppages-DFCciLgG.js",
"build/helppages-DP17w9Oe.js",
"build/helppages-DR34Lvhv.js",
"build/helppages-DTyAGdtV.js",
"build/helppages-DWK3i9kN.js",
"build/helppages-DcFg6_JV.js",
"build/helppages-Dm_u8Ahk.js",
"build/helppages-DmaEkM2O.js",
"build/helppages-DrLUhEa9.js",
"build/helppages-DuKbLzn_.js",
"build/helppages-Dw-9CgX2.js",
"build/helppages-IiN7AcgI.js",
"build/helppages-NSeXFGAQ.js",
"build/helppages-T8lSawP5.js",
"build/helppages-YE6cVcQ-.js",
"build/helppages-b1ipaz7N.js",
"build/helppages-gCVAp8C_.js",
"build/helppages-hhR_Woj-.js",
"build/helppages-imSUu4gQ.js",
"build/helppages-psB09jsM.js",
"build/helppages-z5CfJA7J.js",
"build/main.js",
"build/messages--aGD2rMg.js",
"build/messages-7UTclaK3.js",
"build/messages-B-u6C6YG.js",
"build/messages-B5evcZ42.js",
"build/messages-B6_73IPV.js",
"build/messages-B92TElU6.js",
"build/messages-BCfIKcC_.js",
"build/messages-BS0ni2Cb.js",
"build/messages-BV_AGr40.js",
"build/messages-BZgQSutA.js",
"build/messages-B_HsKxnu.js",
"build/messages-BbfNexWm.js",
"build/messages-BclZwXAr.js",
"build/messages-BdxMgXwG.js",
"build/messages-BeK4JXia.js",
"build/messages-BfiiflEp.js",
"build/messages-BhiY-jX3.js",
"build/messages-Bj4IrsGN.js",
"build/messages-BlNi9_zW.js",
"build/messages-BmQYUyOE.js",
"build/messages-BnH5uVuR.js",
"build/messages-BywB_snn.js",
"build/messages-C-_6iNPo.js",
"build/messages-C2MgWJ9d.js",
"build/messages-C2TtXFky.js",
"build/messages-C3dQwSXA.js",
"build/messages-C4I5kW00.js",
"build/messages-C4ZtfyKT.js",
"build/messages-C88525Cl.js",
"build/messages-CClFq_wk.js",
"build/messages-CIXTdf-H.js",
"build/messages-CJY1tCnA.js",
"build/messages-CKly3XoI.js",
"build/messages-CLbvgmIL.js",
"build/messages-CU1JqKM3.js",
"build/messages-CYCeJ3Nu.js",
"build/messages-Ca3qD-de.js",
"build/messages-Cd-p8hJ5.js",
"build/messages-CdSfGbqv.js",
"build/messages-Cig5zRT4.js",
"build/messages-ClZYmO5p.js",
"build/messages-CoUsPdZT.js",
"build/messages-CpTL8nIA.js",
"build/messages-Croq-Fxd.js",
"build/messages-CxhRDGj7.js",
"build/messages-D-EYgLHN.js",
"build/messages-DCYTM12d.js",
"build/messages-DCmPUG98.js",
"build/messages-DDZpJZj4.js",
"build/messages-DGFkANex.js",
"build/messages-DHKPKe3j.js",
"build/messages-DJ-oF0Qq.js",
"build/messages-DP3SRMwt.js",
"build/messages-DRsORDm7.js",
"build/messages-DVdhTjtL.js",
"build/messages-DWWDlNV7.js",
"build/messages-DYlromDg.js",
"build/messages-DZkqC_RE.js",
"build/messages-D_ulLktf.js",
"build/messages-Da6zhpy1.js",
"build/messages-DbOwgbWh.js",
"build/messages-Dbf3tNsf.js",
"build/messages-DbsN9xIT.js",
"build/messages-Dg8vkCyc.js",
"build/messages-Doi9xgk4.js",
"build/messages-DsSMslhp.js",
"build/messages-Du6IoKX9.js",
"build/messages-DubBHhML.js",
"build/messages-DwNue2Cz.js",
"build/messages-Dxb_aXbX.js",
"build/messages-DyvGXv43.js",
"build/messages-JhyKvoKl.js",
"build/messages-Q58oyH08.js",
"build/messages-Qn51penC.js",
"build/messages-RE3vh2K8.js",
"build/messages-ZXRtSlaO.js",
"build/messages-_ESiBVmn.js",
"build/messages-b1zePbCI.js",
"build/messages-dO9wYtRz.js",
"build/messages-f4etycts.js",
"build/messages-grRG-cKU.js",
"build/messages-ionQ21da.js",
"build/messages-isFtm6X6.js",
"build/messages-rAyDHWw9.js",
"build/messages-tLjV8bds.js",
"build/messages-uBJSDTfv.js",
"build/messages-uswDD5gw.js",
"build/messages-wIXPe5I3.js",
"build/osmc_symbols.js",
"img/ajax-loader.gif",
"img/banner_cycling.jpg",
"img/banner_hiking.jpg",
"img/banner_mtb.jpg",
"img/banner_riding.jpg",
"img/banner_skating.jpg",
"img/banner_slopes.jpg",
"img/dot.png",
"img/guidepost.svg",
"img/logo_background.svg",
"img/map_cycling.ico",
"img/map_cycling.png",
"img/map_cycling.svg",
"img/map_hiking.ico",
"img/map_hiking.png",
"img/map_hiking.svg",
"img/map_mtb.ico",
"img/map_mtb.png",
"img/map_mtb.svg",
"img/map_riding.ico",
"img/map_riding.png",
"img/map_riding.svg",
"img/map_skating.ico",
"img/map_skating.png",
"img/map_skating.svg",
"img/map_slopes.ico",
"img/map_slopes.png",
"img/map_slopes.svg",
"img/marker.png",
"img/route_alp.png",
"img/route_hike.png",
"img/route_int.png",
"img/route_mnt.png",
"img/route_mnt1.png",
"img/route_mnt2.png",
"img/route_nat.png",
"img/route_nordic.png",
"img/route_other.png",
"img/route_reg.png",
"img/route_ski.png",
"img/route_sled.png",
"img/route_std.png",
"img/route_unknown.png",
"img/waymarked_trails_logo.svg",
"img/white.svg",
"img/white_blue_bar.svg",
"img/white_red_bar.svg",
"img/yellow_diamond.svg"
];

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(SHELL).then(function (c) {
    return Promise.all(FILES.map(function (f) {
      return c.add(new Request(f, { cache: 'no-cache' })).catch(function () {});
    }));
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) {
      return k.indexOf('app-') === 0 && k !== SHELL;
    }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

function trim(cache, max) {
  return cache.keys().then(function (keys) {
    if (keys.length <= max) return;
    return Promise.all(keys.slice(0, keys.length - max).map(function (k) { return cache.delete(k); }));
  });
}

// Map pictures: saved copy first (works offline), else download and save.
var TILE_HOSTS = /(^|\.)tile\.openstreetmap\.org$|^tile\.waymarkedtrails\.org$|^tile\.openmaps\.fr$|^hillshading\.waymarkedtrails\.org$|^static\.waymarkedtrails\.org$/;
function isVectorTile(url) { return url.hostname === 'hiking.waymarkedtrails.org' && /^\/api\/v1\/(tiles|symbols)\//.test(url.pathname); }
function isApi(url) { return url.hostname === 'hiking.waymarkedtrails.org' && url.pathname.indexOf('/api/') === 0; }

function cacheFirst(req, name, max) {
  return caches.open(name).then(function (cache) {
    return cache.match(req.url).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && (res.ok || res.type === 'opaque')) {
          cache.put(req.url, res.clone()).then(function () { return trim(cache, max); });
        }
        return res;
      });
    });
  });
}

function networkFirst(req, name, key, max) {
  return fetch(req).then(function (res) {
    if (res && res.ok) {
      var copy = res.clone();
      caches.open(name).then(function (c) { return c.put(key, copy).then(function () { return max && trim(c, max); }); });
    }
    return res;
  }).catch(function () {
    return caches.open(name).then(function (c) { return c.match(key, { ignoreSearch: name === SHELL }); }).then(function (hit) {
      if (hit) return hit;
      throw new Error('offline');
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);

  if (TILE_HOSTS.test(url.hostname) || isVectorTile(url)) {
    e.respondWith(cacheFirst(req, TILES, MAX_TILES));
    return;
  }
  if (isApi(url)) {
    // Trail details, lists and search: fresh online, last copy offline.
    e.respondWith(networkFirst(req, DATA, req.url, MAX_DATA));
    return;
  }
  if (url.origin === self.location.origin) {
    if (req.mode === 'navigate') {
      e.respondWith(fetch(req, { cache: 'no-cache' }).catch(function () {
        return caches.open(SHELL).then(function (c) { return c.match(url.pathname.endsWith('/') ? './' : req, { ignoreSearch: true }); })
          .then(function (hit) { return hit || caches.match('index.html', { cacheName: SHELL }); });
      }));
      return;
    }
    e.respondWith(caches.open(SHELL).then(function (c) {
      return c.match(req, { ignoreSearch: true }).then(function (hit) {
        return hit || fetch(req).then(function (res) {
          if (res.ok) c.put(req, res.clone());
          return res;
        });
      });
    }));
  }
});
