"""Generate public/sw.js (offline support) and the app manifest after `rollup -c`.

Run:  npx rollup -c && python3 make_sw.py
"""
import hashlib, json, os

PUB = os.path.join(os.path.dirname(__file__), 'public')

files = ['./', 'index.html', 'hiking.css', 'manifest.webmanifest', 'icon-192.png', 'icon-512.png']
for root, _, names in os.walk(os.path.join(PUB, 'build')):
    for n in sorted(names):
        if not n.endswith('.map'):
            files.append(os.path.relpath(os.path.join(root, n), PUB))
for n in sorted(os.listdir(os.path.join(PUB, 'img'))):
    files.append('img/' + n)

h = hashlib.sha1()
for f in files:
    p = os.path.join(PUB, f) if f != './' else os.path.join(PUB, 'index.html')
    if os.path.isfile(p):
        h.update(open(p, 'rb').read())
version = h.hexdigest()[:10]

sw = """// Sentieri: offline support. Generated by make_sw.py, do not edit by hand.
var VERSION = '%(version)s';
var SHELL = 'app-' + VERSION;
var TILES = 'tiles-v1';
var DATA = 'data-v1';
var MAX_TILES = 8000;
var MAX_DATA = 1500;
var FILES = %(files)s;

self.addEventListener('install', function (e) {
  e.waitUntil(caches.open(SHELL).then(function (c) {
    return Promise.all(FILES.map(function (f) {
      return c.add(new Request(f, { cache: 'no-cache' })).catch(function () {});
    }));
  }).then(function () { return self.skipWaiting(); }));
});

self.addEventListener('activate', function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.filter(function (k) {
      return k.indexOf('app-') === 0 && k !== SHELL;
    }).map(function (k) { return caches.delete(k); }));
  }).then(function () { return self.clients.claim(); }));
});

function trim(cache, max) {
  return cache.keys().then(function (keys) {
    if (keys.length <= max) return;
    return Promise.all(keys.slice(0, keys.length - max).map(function (k) { return cache.delete(k); }));
  });
}

// Map pictures: saved copy first (works offline), else download and save.
var TILE_HOSTS = /(^|\\.)tile\\.openstreetmap\\.org$|^tile\\.waymarkedtrails\\.org$|^tile\\.openmaps\\.fr$|^hillshading\\.waymarkedtrails\\.org$|^static\\.waymarkedtrails\\.org$/;
function isVectorTile(url) { return url.hostname === 'hiking.waymarkedtrails.org' && /^\\/api\\/v1\\/(tiles|symbols)\\//.test(url.pathname); }
function isApi(url) { return url.hostname === 'hiking.waymarkedtrails.org' && url.pathname.indexOf('/api/') === 0; }

function cacheFirst(req, name, max) {
  return caches.open(name).then(function (cache) {
    return cache.match(req.url).then(function (hit) {
      if (hit) return hit;
      return fetch(req).then(function (res) {
        if (res && (res.ok || res.type === 'opaque')) {
          cache.put(req.url, res.clone()).then(function () { return trim(cache, max); });
        }
        return res;
      });
    });
  });
}

function networkFirst(req, name, key, max) {
  return fetch(req).then(function (res) {
    if (res && res.ok) {
      var copy = res.clone();
      caches.open(name).then(function (c) { return c.put(key, copy).then(function () { return max && trim(c, max); }); });
    }
    return res;
  }).catch(function () {
    return caches.open(name).then(function (c) { return c.match(key, { ignoreSearch: name === SHELL }); }).then(function (hit) {
      if (hit) return hit;
      throw new Error('offline');
    });
  });
}

self.addEventListener('fetch', function (e) {
  var req = e.request;
  if (req.method !== 'GET') return;
  var url = new URL(req.url);

  if (TILE_HOSTS.test(url.hostname) || isVectorTile(url)) {
    e.respondWith(cacheFirst(req, TILES, MAX_TILES));
    return;
  }
  if (isApi(url)) {
    // Trail details, lists and search: fresh online, last copy offline.
    e.respondWith(networkFirst(req, DATA, req.url, MAX_DATA));
    return;
  }
  if (url.origin === self.location.origin) {
    if (req.mode === 'navigate') {
      e.respondWith(fetch(req, { cache: 'no-cache' }).catch(function () {
        return caches.open(SHELL).then(function (c) { return c.match(url.pathname.endsWith('/') ? './' : req, { ignoreSearch: true }); })
          .then(function (hit) { return hit || caches.match('index.html', { cacheName: SHELL }); });
      }));
      return;
    }
    e.respondWith(caches.open(SHELL).then(function (c) {
      return c.match(req, { ignoreSearch: true }).then(function (hit) {
        return hit || fetch(req).then(function (res) {
          if (res.ok) c.put(req, res.clone());
          return res;
        });
      });
    }));
  }
});
""" % {'version': version, 'files': json.dumps(files, indent=0)}

open(os.path.join(PUB, 'sw.js'), 'w').write(sw)

manifest = {
    "name": "Sentieri",
    "short_name": "Sentieri",
    "description": "Mappa dei sentieri con Waymarked Trails, utilizzabile offline",
    "start_url": "./",
    "scope": "./",
    "display": "standalone",
    "background_color": "#2f4a2b",
    "theme_color": "#2f4a2b",
    "lang": "it",
    "icons": [
        {"src": "icon-192.png", "sizes": "192x192", "type": "image/png"},
        {"src": "icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "any maskable"}
    ]
}
json.dump(manifest, open(os.path.join(PUB, 'manifest.webmanifest'), 'w'), indent=2, ensure_ascii=False)
print('sw.js version', version, '-', len(files), 'files precached')
